### ISSUE TITLE
Disable entities, change from bits to Mbits/s

### ISSUE THREAD

**Issue by GnFlala** [elad-bar/ha-edgeos#113]
I can do both but every now and then all entities gets enabled again and Mbits/s reverts to bits.

Its like everything gets reseted.

**Comment by illuzn** [comment]
To add to the above.

It's not that the entities get resetted. It's that whole new entities are added to Home Assistant.

This has happened to me 3 times now and I have 3 copies of "EDGEROUTER12 Interface ETH9" in my devices (as well as every other device/ entity).

It appears to have something to do with restarting Home Assistant (but it is not every time that there is a restart) because it happened to me 2 hours ago which is when I installed an update to Home Assistant.

**Comment by elad-bar** [comment]
will check it out soon, thanks for reporting that issue

**Comment by elad-bar** [comment]
Fixed it in in v2.1.x,
Please check

Thanks

**Comment by elad-bar** [comment]
Fixed in v2.1.x
