### ISSUE TITLE
Monitored Interfaces stops working after a couple of hours

### ISSUE THREAD

**Issue by joostvanmourik** [elad-bar/ha-edgeos#40]
Hi,

I used this component on two seperate installations (docker on synology) and now docker on a PI4. But both times the component stop refreshing information after a couple of hours. Any idea how to solve this

**Comment by elad-bar** [comment]
for me it's working pretty stable, but I can guess the code is not 100% bullet proof, how many times it happens in a week?
asking because maybe you can enable the logs in debug mode for that component only (available in Integrations -> EdgeOS -> Options) and once it happens share with me the logs from that period of time, 
using that information I'll be able to understand the issue and solve it

thanks

**Comment by elad-bar** [comment]
Is it still relevant?  In case it does, which version of edgeos are you using?
