### ISSUE TITLE
Failed to connect after installing Home Assistant 2021.1.3 Security update

### ISSUE THREAD

**Issue by basdejong95** [elad-bar/ha-edgeos#44]
Failed to connect EdgeOS WS, Error: 400, message='Invalid response status', url=URL('wss://192.168.1.1/ws/stats')

is the message that i am getting. Worked perfectly before this update!

Extra info:

Logger: custom_components.edgeos.clients.web_socket
Source: custom_components/edgeos/clients/web_socket.py:91
Integration: Ubiquiti EdgeOS Routers (documentation)
First occurred: 4:41:13 PM (14 occurrences)
Last logged: 4:42:53 PM

Failed to connect EdgeOS WS, Error: 400, message='Invalid response status', url=URL('wss://192.168.1.1/ws/stats')

**Comment by fintmu** [comment]
Same here. After installing Home Assistant 2021.1.3 this integration stopped working.

**Comment by AlTyndall** [comment]
Same for me today when I updated HA.

**Comment by elad-bar** [comment]
For me it's still working, 
I will check it later today,
Can you please provide debug log level logs just for that component including which version are you using,
Whether your certificate of SSL is CA / self-signed or default and whether you are using IP, hostname or fully qualified domain name 

Thanks

**Comment by esukka** [comment]
Same issue here. I'm using internal ip, no ssl certificates etc. Just plain internal access with username and password. I removed and readded the integration, all interfaces shows offline, but system_status, unknown_devices and system uptime sensors seems to be fine.

**Comment by fintmu** [comment]
I just updated my EdgeRouter X to the latest firmware (v2.0.9) and after that the integration is working again normally.

**Comment by AlTyndall** [comment]
Afraid I deleted the integration, so I wouldn't know now where to go to get the logs. My EdgeMax threw a bit of a wobbly this morning, and I wondered whether it had anything to do with the integration - I know it shouldn't have done, but I got a message from Nabu Casa advising me to remove all custom integrations and to update to 2021.1.3 (which I had), and since the integration was showing status as disconnected and no uptime I wondered whether the two were related. While it is nice to have the status of my devices connected to a stationary router, it's not a deal breaker just yet.
I was only connected internally to the local IP address. No SSL as far as I am aware. Only running 1.10.8 firmware on EdgeMax - if it ain't broke... Was a bit wary of going to 2.x because of breaking changes a couple of years ago, and haven't bothered to look at it since.

**Comment by elad-bar** [comment]
I can understand your concern result of the panic, but it's not like HA added something that will make the HA bullet proof,
Please read the last post of the forum (related to the announcement) as it describes how your data already sent to 3rd party as part of other integrations you might use,
It's up to you to decide, BTW, leaving your router with older version exposes your network to much wider risks, I suggest for you to upgrade no matter if you are going to use the component or not,
The fact you are not using SSL is another risk, also suggest to have such one,
Anyway, the component is just reading from the router not performing any action (although I would like to add in the future)

Thanks

**Comment by basdejong95** [comment]
> I just updated my EdgeRouter X to the latest firmware (v2.0.9) and after that the integration is working again normally.

Thanks for the tip! i was running the v1.something firmware and i updated to 2.0.9 and now it also works!

**Comment by elad-bar** [comment]
Great, thanks for the update

**Comment by villain** [comment]
is there a solution for this other than upgrading to v2, which is still plagued by a few major bugs?

**Comment by elad-bar** [comment]
I don't have that version, i can't reproduce, fix and test it
