### ISSUE TITLE
General failure error message

### ISSUE THREAD

**Issue by wlraider70** [elad-bar/ha-edgeos#54]
Hi, I keep getting "General failure, please try again"

edgemax - EdgeRouter X v2.0.8-hotfix.1
v.1.1.4 of integration.
made new user/password
rebooted device.

**Comment by Northcountry** [comment]
Just started getting the same error after upgrading to v1.1.4 of EdgeOS custom component and running  EdgeRouter X v2.0.8 . It has been working with no issues for months and now getting this error.

2021-08-24 22:31:34 WARNING (MainThread) [custom_components.edgeos.managers.config_flow_manager] Failed to login EdgeOS EdgeOS due to general error: 'NoneType' object is not subscriptable

I tried downgrading the EdgeOS component but still not able to get logged back into ERX from component. Have removed it and readded but still no luck.

**Comment by elad-bar** [comment]
Dup #53 

will be fixed soon with v1.1.5
