### ISSUE TITLE
Integration will not work correctly since DPI (deep packet inspection) is turned off and Traffic Analysis Export is turned off

### ISSUE THREAD

**Issue by ALERTua** [elad-bar/ha-edgeos#73]
The integration spams the log with
`Integration will not work correctly since DPI (deep packet inspection) is turned off and Traffic Analysis Export is turned off`
Yes, I know, that my router has DPI and Traffic Analysis Export turned off, I don't need the functionality based on these services. The integration offers much more.
I would appreciate a setup flag to ignore the missing DPI and TA.
Thank you

**Comment by elad-bar** [comment]
You actually need it, the ws subscription is looking for 2 topics that resulted by that configuration, this is mentioned as well in the readme since day 1, now i have added that warning as people tend to skip reading the manual and keep asking me why it's not working, now they have the log message that explains
