### ISSUE TITLE
Config port isn't used to connect to EdgeOS

### ISSUE THREAD

**Issue by ALERTua** [elad-bar/ha-edgeos#74]
The Port configuration value isn't used to connect to EdgeOS, the URL only forms out of the hardcoded HTTPS protocol and Host value. Maybe it would be better to rename Host to URL and remove the Port key?
Thank you

**Comment by elad-bar** [comment]
I thought about it as well, but some of the poeple over the time talked with me about issue with connectivity and it was because the were using reverse proxy with different port, so to support these users i have set the default port as 443 without option to change the protocol to non-secured (ws / http) and kept it within the configuration ui

**Comment by elad-bar** [comment]
just so that it is not in use at whole, removing it for next version, thanks

**Comment by elad-bar** [comment]
removed, please let me know if it looks better

thanks
